version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    volumes:
      - './web:/var/www/html'
  db:
    image: mysql:8.0
    ports: 
        - 3306:3306
    command: >
          bash -c "
          chmod 644 /etc/mysql/conf.d/*.cnf
          && /entrypoint.sh mysqld
          "
    environment:
        MYSQL_DATABASE: labo4
        MYSQL_ROOT_PASSWORD: test 
    volumes:
        - ./scripts:/docker-entrypoint-initdb.d
        - ./conf:/etc/mysql/conf.d
    networks:
        - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
        - db:db
    ports:
        - 8000:80
    environment:
        MYSQL_ROOT_PASSWORD: test 
